name: lyra_mobile
description: Lyra — мобильное приложение для 1С:Предприятие
publish_to: 'none'
version: 0.4.0+9

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  centrifuge: ^0.14.0
  mobile_scanner: ^5.0.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.0
  uuid: ^4.0.0
  go_router: ^14.0.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
